(xsession) add T650 touchpad to x11-set-mouse-prefs and xinput command-check guard

diff --git a/xsession/.local/scripts/x11-set-mouse-prefs b/xsession/.local/scripts/x11-set-mouse-prefs
--- a/xsession/.local/scripts/x11-set-mouse-prefs
+++ b/xsession/.local/scripts/x11-set-mouse-prefs
@@ -13,6 +13,11 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+if ! command -v xinput >/dev/null </dev/null 2>&1; then
+    echo "xinput: command not found" >&2
+    exit 1
+fi
+
 xinput set-prop \
     pointer:'Logitech MX Anywhere 2' \
     'libinput Natural Scrolling Enabled' 1
@@ -36,3 +41,27 @@ xinput set-prop \
 xinput set-prop \
     pointer:'Clearly Superior Technologies. CST Laser Trackball' \
     'libinput Accel Speed' -0.35
+
+xinput set-prop \
+    pointer:'Logitech Rechargeable Touchpad T650' \
+    'Synaptics Finger' 1 12 0
+
+xinput set-prop \
+    pointer:'Logitech Rechargeable Touchpad T650' \
+    'Synaptics ClickPad' 0
+
+xinput set-prop \
+    pointer:'Logitech Rechargeable Touchpad T650' \
+    'Synaptics Two-Finger Scrolling' 1 1
+
+xinput set-prop \
+    pointer:'Logitech Rechargeable Touchpad T650' \
+    'Synaptics Tap Action' 0 0 0 0 1 3 2
+
+xinput set-prop \
+    pointer:'Logitech Rechargeable Touchpad T650' \
+    'Synaptics Click Action' 0 0 0
+
+xinput set-prop \
+    pointer:'Logitech Rechargeable Touchpad T650' \
+    'Synaptics Scrolling Distance' -73 -73
